title: Anne Chew's Blog
description: > 
  Anne's personal blog, to share my thoughts about what documentation
  practices, tools, etc.
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "https://annecyh.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Anne Chew # add your name
author-img: annechewyiihuei.jpg # add your photo
about-author: > # add description
  A technical author who translates "Engineering language" to English.
  Experienced in software and API reference documentation. Always eager to
  explore new areas and learn new skills.
social-twitter: # add your Twitter handle
social-facebook: AnneCYHPhotography # add your Facebook handle
social-github: annecyh # add your Github handle
social-linkedin: anne-yii-huei-chew-1bb97626 # add your Linkedin handle
social-email: ayhchew@yahoo.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
